export const projects = [
  {
    title:
      "YelpCamp",
    description: `A website where users can create and review campgrounds with a map. The website has a RESTful routing, user authentication, and authorization. Users can upload their own campgrounds and review other campgrounds.`,
    img: "/yelpcamp.png",
    href: "/projects/yelpcamp",
    preview: "https://yelpcampofsidd.onrender.com/home",
    github: "https://github.com/Sidd-77/yelpCamp",
    alt: "Projects",
    platform: "Web",
    stack: "HTML, Bootstrap, Javascript, NodeJs, ExpressJs, MongoDB.",
    delay: 0.1,
  },
  {
    title: "Message Punk",
    description: `It is a chat app build in MERN stack with TypeScript, NextUi library for frontend and Socket.io for real-time communication It has most features implemented necessary in a chat app like real-time messaging, typing indicator, creating groups, editing group members and information, and many more...`,
    img: "/messagepunk.png",
    href: "/projects/messagepunk",
    preview: "https://messenger-o-punk.vercel.app/",
    github: "https://github.com/Sidd-77/messengerOpunk",
    alt: "Projects",
    platform: "Web",
    stack: "ReactJs, Typescript, NextUi, NodeJs, ExpressJs, MongoDB, Socket.io.",
    delay: 0.1,
  },
  {
    title: "ResNet Model",
    description: `Model to classify images using ResNet architecture. It is a deep residual learning model that is capable of classifying images with high accuracy. It is trained on the CIFAR-10 dataset and has an accuracy of 90% on the test set.`,
    img: "/E-Commerce.png",
    href: "/projects/resnet",
    preview: "https://github.com/Sidd-77/ml-models",
    github: "https://github.com/Sidd-77/ml-models",
    alt: "Projects",
    platform: "Jyupter Notebook, Python",
    stack: "Numpy, Tensorflow, Keras, Matplotlib, Jupyter Notebook.",
    delay: 0.1,
  },
  {
    title: "Simple Nerural Network",
    description: `A simple 2 layer neural network to detect digit between 0 and 9 trainined on MNIST dataset.`,
    img: "/Design-System.png",
    href: "/projects/nn",
    preview: "https://github.com/Sidd-77/nn-basic/blob/main/nn.ipynb",
    github: "https://github.com/Sidd-77/nn-basic/blob/main/nn.ipynb",
    alt: "Projects",
    platform: "Jyupter Notebook, Python",
    stack: "Numpy, Pandas, Matplotlib, Jupyter Notebook",
    delay: 0.2,
  },
  
];
