export const projects = [
  {
    title: "YelpCamp",
    description: `A website where users can create and review campgrounds with a map. The website has a RESTful routing, user authentication, and authorization. Users can upload their own campgrounds and review other campgrounds.`,
    img: "/yelpcamp.png",
    href: "/projects/yelpcamp",
    preview: "https://yelpcampofsidd.onrender.com/home",
    github: "https://github.com/Sidd-77/yelpCamp",
    alt: "Projects",
    platform: "Web",
    stack: "HTML, Bootstrap, Javascript, NodeJs, ExpressJs, MongoDB.",
    delay: 0.1,
  },
  {
    title: "Message Punk",
    description: `It is a chat app build in MERN stack with TypeScript, NextUi library for frontend and Socket.io for real-time communication It has most features implemented necessary in a chat app like real-time messaging, typing indicator, creating groups, editing group members and information, and many more...`,
    img: "/messagepunk.png",
    href: "/projects/messagepunk",
    preview: "https://messenger-o-punk.vercel.app/",
    github: "https://github.com/Sidd-77/messengerOpunk",
    alt: "Projects",
    platform: "Web",
    stack:
      "ReactJs, Typescript, NextUi, NodeJs, ExpressJs, MongoDB, Socket.io.",
    delay: 0.1,
  },
  {
    title: "Student Performance Prediction",
    description: `Simple end-to-end ml project to predict student performance.`,
    img: "/studentperformance.png",
    href: "/projects/studentperformanceprediction",
    preview: "https://ml-project-6zb2.onrender.com/",
    github: "https://github.com/Sidd-77/ml_project",
    alt: "Projects",
    platform: "Web",
    stack: "Stramlit, Scikit-Learn, Pandas, Python.",
    delay: 0.1,
  },
  {
    title: "Simple Nerural Network",
    description: `A simple 2 layer neural network to detect digit between 0 and 9 trainined on MNIST dataset.`,
    img: "/nn.png",
    href: "/projects/nn",
    preview: "https://github.com/Sidd-77/nn-basic/blob/main/nn.ipynb",
    github: "https://github.com/Sidd-77/nn-basic/blob/main/nn.ipynb",
    alt: "Projects",
    platform: "Jyupter Notebook, Python",
    stack: "Numpy, Pandas, Matplotlib, Jupyter Notebook",
    delay: 0.2,
  },
  {
    title: "Code Submissions",
    description: `This project is a full-stack web application built with Express.js, MySQL, Redis, React, and Next UI. It uses Express.js for the backend, MySQL for the database, Redis for caching, React for the frontend, and Next UI for the UI library. It also executes code online using Judge0 api although impletention is partial.`,
    img: "/codesubmission.png",
    href: "/projects/codesubmission",
    preview: "https://task-swart-five.vercel.app/",
    github: "https://github.com/Sidd-77/task",
    alt: "Projects",
    platform: "Web",
    stack: "React, NextUi, Express, NodeJs, Redis, MySQL",
    delay: 0.2,
  },
  {
    title: "Personal Porfolio Website",
    description: `It is my personal portfolio website crafted with Next.js and elevated with NextUI! written in Typescript.`,
    img: "/portfolio.png",
    href: "/projects/codesubmission",
    preview: "https://task-swart-five.vercel.app/",
    github: "https://github.com/Sidd-77/task",
    alt: "Projects",
    platform: "Web",
    stack: "React, NextUi, Express, NodeJs, Redis, MySQL",
    delay: 0.2,
  },
  {
    title: "Collection of small full stack applications",
    description: `These are collection of full stack applications I created for academic work.`,
    img: "/Design-System.png",
    href: "/projects/codesubmission",
    preview: "https://github.com/Sidd-77/adb_assignments",
    github: "https://github.com/Sidd-77/adb_assignments",
    alt: "Projects",
    platform: "Web",
    stack: "React, NextUi, Express, NodeJs, MySQL",
    delay: 0.2,
  },
];
